# Generated by Django 5.0.7 on 2024-09-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='std',
            old_name='mark',
            new_name='roll',
        ),
    ]
